name: GitHub Package publishing with Maven

on:
  release:
    types: [created]

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        server-id: github-esql-stmt
        settings-path: ${{ github.workspace }}

    - name: Publish to GitHub Packages
      run: mvn -B -DskipTests --no-transfer-progress --update-snapshots package deploy -s $GITHUB_WORKSPACE/settings.xml --file pom.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - uses: actions/upload-artifact@v4
      with:
        name: jar-packaging
        path: target/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
